### PR TITLE
Code enhancement - fix all the issues reported by Pylint

### PR DESCRIPTION
**Pull request by rpelisse**

### CODE REVIEW

**Comment by rpelisse** [comment]
@sabre1041 just in case you did not see this PR

**Comment by sabre1041** [comment]
@rpelisse what is the proper method to validate this enhancement?

**Comment by rpelisse** [comment]
@sabre1041 I'm not sure what you mean here. it's just code enhancement following the issues pointed out by Pylint. It's akin to fixing issues spot by Checkstyle or PMD.

**Review by sabre1041 — APPROVED** [review]
LGTM

**Pull request merged**
