### PR TITLE
Module remote execution refactor

### PR DESCRIPTION
**Pull request by rpelisse**
@sabre1041 As discussed, I’ve refactor the module to use action_plugin to prepare the template and deploy on the target host, before the module is executed itself (again, on the target). I’ve also done some serious cleanup in the code, removing a lot of unnecessary pieces and leveraging the internal API of Ansible

### CODE REVIEW

**Comment by rpelisse** [comment]
please retest this

**Comment by rpelisse** [comment]
@sabre1041 Hum, the setup of the test env in CI seems to be failing. I've tried three times and it fails at the same spot :( (apparently even before automate-jcliff is called). Can you take a look and let me know what you think is happening? Thanks!

**Comment by sabre1041** [comment]
@rpelisse take a look at the Travis test. If you look higher up in the output, you will notice the following Lint failure

```
--> Executing Yamllint on files found in /home/travis/build/redhat-cop/automate-jcliff/...
    /home/travis/build/redhat-cop/automate-jcliff/tune-wildfly-with-jcliff.yml
      32:1      warning  comment not indented like content  (comments-indentation)
```

The comments are causing linting failures

**Comment by rpelisse** [comment]
@sabre1041 Yeah, it's working, JCliff is being called, but now this needs a fix on JCliff to work. I'll commit this fix and release it right away. Can you make yamlint error just spit a warning and not make the build failing? I think it's a bit early in the process to have the build failed for that :)

**Review by sabre1041 — APPROVED** [review]

**Pull request merged**
